### ISSUE TITLE
Why each face background B is 3D vector?

### ISSUE THREAD

**Issue by rjarvinen** [iljah/pamhd#4]
Why each background face B is defined as a 3D vector, shouldn't it be a scalar because only a component perpendicular to the face is stored?

https://github.com/iljah/pamhd/blob/d7f4946babac7b6d02fd932d32a44cd2c4fc968f/source/variables.hpp#L78
https://github.com/iljah/pamhd/blob/d7f4946babac7b6d02fd932d32a44cd2c4fc968f/source/variables.hpp#L86
https://github.com/iljah/pamhd/blob/d7f4946babac7b6d02fd932d32a44cd2c4fc968f/source/variables.hpp#L94

**Comment by iljah** [comment]
Flux calculation at least requires all components: https://github.com/iljah/pamhd/blob/master/source/mhd/common.hpp#L140
Current implementation of staggered field solver also uses solved fluxes.
